[workspace]
resolver = "2"
members = [
    "apps/desktop/src-tauri",
]

[profile.dev]
opt-level = 1

[profile.release]
debug = 1
lto = true
split-debuginfo = "packed"

[profile.profiler]
inherits = "release"
debug = true
split-debuginfo = "unpacked"
strip = "none"
